---
- name: 웹서비스 설정 및 확인
  hosts: web1
  become: yes
  tasks:
    - name:  방화벽에 서비스 등록
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled

    - name: 패키지 삭제
      ansible.builtin.yum:
        name:
          - firewalld
          - httpd
          - mariadb-server
          - php
          - php-mysqlnd
          - php-pdo
        state: absent

    - name: 웹 패키지 다운로드
      get_url:
        url: "http://192.168.10.10/index.php"
        dest: "/var/www/html/index.php"
        mode: 0644