---
- name: 0) Restore the playbook.yml
  hosts: all
  gather_facts: true
  tasks:
    # 1) 방화벽 포트 제거 - http, https
    # 2) 서비스 내리기 - httpd, mariadb
    # 3) 설정 삭제 - /var/www/html/index.html
    # 4) 패키지 삭제 - httpd, mariadb-server

    - name: 1) 방화벽에 포트 제거
      firewalld:
        service:
          - http
          - https
        permanent: true
        immediate: true
        state: absent


    - name: 2) 서비스 내리기
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - httpd
        - mariadb

    - name: 3) 설정 삭제
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 4) 패키지 삭제
      dnf:
        name: "{{ item }}"
        state: absent
      loop:
        - httpd
        - mariadb-server


        














