---
- name: 0) 복구
  hosts: all
  vars:
    packages:
    - mariadb-server
    - python3-PyMySQL
    svc_db : mariadb
  tasks:
    - name: DB 패키지 제거 - mariadb-server, python-PyMySQL
      dnf:
        name: "{{ item }}"
        state: absent
      loop: "{{ packages }}"

      when: ansible_distribution == 'CentOS'

  
