---
- name: 복구 작업
  hosts: all
  tasks:
    - name: 방화벽 포트 닫기
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: disabled
        immediate: true
    - name: 서비스 닫기
      ansible.builtin.service:
        name: httpd
        state: stopped
        enabled: false
    - name: 인덱스 삭제
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 패키지 지우기
      ansible.builtin.dnf:
        name: httpd
        state: absent
        


