---
- name: 타임존 설정
  hosts: all
  vars:
   - timezone : Asia/Seoul

  roles:
    - rhel-system-roles.timesync

  post_tasks:
    - name: 타임존 설정
      community.general.timezone:
        name: "{{ timezone }}"
      notify: restart chronyd

  handlers:
    - name: restart chronyd
      ansible.builtin.service:
        name: chronyd
        state: restarted